### ISSUE TITLE
Link ships to the pilot's last loss in that ship

### ISSUE THREAD

**Issue by evidex** [haggen/localthreat#17]
A useful piece of information to see would be the "Top Ship" field from zKill for searched characters.   It would also be possible to link to a zKill result showing the characters losses for this ship type, allowing you to quickly check for an expected fit.

Mockup:
https://i.imgur.com/AaRfmao.png

**Comment by haggen** [comment]
Hey @evidex thank you for your request! I've got good news for you. It seems for some mysterious reason (probably my fault) you're seeing an old version of the site. Could you please try clearing the cache of your browser and try again visiting https://localthreat.xyz/ to see if you get the newest version? The newest version features the top recently used ships by each pilot listed, as you can see below:

![screenshot from 2018-01-05 11 49 32](https://user-images.githubusercontent.com/270076/34611921-b7199e42-f20e-11e7-85df-9a37e42ceec4.png)

Although they link to the ship's generic page in zKillboard, changing it to the pilot's last last loss in that ship would be great! I'll make this issue about this change, since half of what you asked is already in place. 

Feel free to open new issue and/or comment below if you have any more issues or suggestions!

**Comment by evidex** [comment]
@haggen Yup, clearing the cached storage via Chrome Devtools shows me the newer site version. Thanks!

**Comment by haggen** [comment]
@evidex Could you provide me your browser's name and version? I'm trying to find out why some people are have cache problems.

**Comment by haggen** [comment]
@evidex I couldn't link the ships directly to the character's last loss, but I managed the next best thing. Ships now link to that character's killboard filtering kills and losses where he used that ship. So all you have to do is look for a loss and click to check their fitting. Plus I think I fixed the problem with caching. Let me know if you have any other issues!
